[package]
name = "alvr_openvr_driver"
version = "0.1.0"
authors = ["alvr-org"]
license = "MIT"
edition = "2021"
rust-version = "1.56"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.59"
cbindgen = "0.20"
cc = "1"
regex = "1"